micronaut:
  application:
    name: superHeroes
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/superhero`}
    username: ${JDBC_USER:dbuser}
    password: ${JDBC_PASSWORD:theSecretPassword}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}
    schema-generate: CREATE_DROP
    dialect: POSTGRES
logger:
  levels:
    ROOT: INFO

  #cache related
  caches:
    superheroes:
      charset: 'UTF-8'
    superhero:
      charset: 'UTF-8'
endpoints:
  caches:
    enabled: true
    sensitive: false

